### ISSUE TITLE
使用fcitx5-rime时一些功能失效

### ISSUE THREAD

**Issue by free-150** [fcitx-contrib/fcitx5-macos#101]
使用 fcitx5-rime 插件。设置了 Ctrl+Shift+F 为切换繁体中文的快捷键但无效。
类似的还有 Ctrl+Shift+x 这样的基本都无效。我还发现一个内置的 Ctrl+Shift+U 快捷键为Unicode码输入，能否供写一个开关供用户关闭这些内置快捷键。
这些问题基本和 fcitx5-android 一模一样。在Linux上 Fcitx5-rime 却没有这些问题。

<img width="284" alt="图片" src="https://github.com/fcitx-contrib/fcitx5-macos/assets/92285544/3e225255-734f-49c8-945b-7f87df8d706a">

<img width="823" alt="图片" src="https://github.com/fcitx-contrib/fcitx5-macos/assets/92285544/650bfad6-3ae0-4095-8930-8c9bbaafc300">

**Comment by eagleoflqj** [comment]
rime官方推荐的一套配置跨平台做法是把带shift和不带shift的字符都写上
https://github.com/rime/rime-prelude/blob/dd84abecc33f0b05469f1d744e32d2b60b3529e3/key_bindings.yaml#L44-L53

雾凇拼音有更详细解释
https://github.com/iDvel/rime-ice/blob/7ea7a678855aae794e922649f9fd9629e60a797a/default.yaml#L198-L199

当前的做法和鼠须管是一致的

**Comment by free-150** [comment]
确实是Control+Shift+F中的F大写的引起的。fcitx5-android 也是大写引起的

**Comment by eagleoflqj** [comment]
Unicode快捷键关闭，关联 https://github.com/fcitx5-android/fcitx5-android/issues/462#issuecomment-2041066804
