### ISSUE TITLE
down跟up无法翻页。。。第一次用这个是哪里设置出错了吗

### ISSUE THREAD

**Issue by scccy** [fcitx-contrib/fcitx5-macos#104]

**Comment by eagleoflqj** [comment]
拼音用上下箭头、-=、PageUp/PageDown翻页
中州韵用-=、PageUp/PageDown翻页
哈利路亚只有一页，不能翻
鼠标悬浮在候选窗时，滚轮可以翻页，触摸板双指也可翻页
在 附加组件配置->WebPanel 设置显示翻页按钮，则可点击按钮翻页

**Comment by scccy** [comment]
就是拼音的pagedown跟up失效了只能用-=

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Qijia Liu ***@***.***>
发送时间: Thursday, April 11, 2024 9:04:44 PM
收件人: fcitx-contrib/fcitx5-macos ***@***.***>
抄送: scccy ***@***.***>; Author ***@***.***>
主题: Re: [fcitx-contrib/fcitx5-macos] down跟up无法翻页。。。第一次用这个是哪里设置出错了吗 (Issue #104)


拼音用上下箭头、-=、PageUp/PageDown翻页
中州韵用-=、PageUp/PageDown翻页
哈利路亚只有一页，不能翻
鼠标悬浮在候选窗时，滚轮可以翻页，触摸板双指也可翻页
在 附加组件配置->WebPanel 设置显示翻页按钮，则可点击按钮翻页

―

**Comment by scccy** [comment]
另外添加词库的时候报错
<img width="682" alt="image" src="https://github.com/fcitx-contrib/fcitx5-macos/assets/29171795/d6dfb6c9-a616-4369-880a-3762ad0a2378">

**Comment by scccy** [comment]
<img width="882" alt="image" src="https://github.com/fcitx-contrib/fcitx5-macos/assets/29171795/127c0a3f-1414-4e66-ad13-3e0c05e182d1">
我更新了版本，然后使用翻页大时候字符就直接消失了

**Comment by eagleoflqj** [comment]
感谢汇报，已修复

**Comment by eagleoflqj** [comment]
> 另外添加词库的时候报错

已于 #112 支持
