### ISSUE TITLE
关于输入法图标

### ISSUE THREAD

**Issue by eagleoflqj** [fcitx-contrib/fcitx5-macos#144]
如你所见，macOS原生的输入法图标是灰度圆角矩形，但小企鹅保留了Linux上的彩色企鹅图标。
这是因为开发团队没有设计师，无法做出有特色、审美在线且和原生相容的图标。
类似情况见[哈利路亚输入法](https://github.com/dongyuwei/hallelujahIM/issues/16)。
本着开源让大家各取所长的理念，如果你的方案能做到

* 得到其他用户认可（请将截图发在此issue下，其他用户👍 👎投票）
* 有辨识度
* 自适应深浅
* 矢量图（正例：微信输入法的pdf图标，可用VSCode打开），不依赖专有软件编辑（反例：鼠须管的pdf图标使用了Adobe Illustrator）

小企鹅将会使用。

除投稿外，本issue不接受无信息量的评论（如：期待早日和系统样式协调）。
也请不要另开issue讨论图标。
感谢理解，祝你打字愉快。

**Comment by XYZSUN** [comment]
![Artboard 1-80](https://github.com/fcitx-contrib/fcitx5-macos/assets/113161159/18649149-8bde-4e34-b69c-907bfc8e6467)
![Artboard 2-80](https://github.com/fcitx-contrib/fcitx5-macos/assets/113161159/fd5635ee-77c9-4b91-b2b5-2f6c6ba9586c)

**Comment by XYZSUN** [comment]
![小企鹅logo](https://github.com/fcitx-contrib/fcitx5-macos/assets/113161159/83b96a14-df62-413b-a9d8-252a23c79733)

**Comment by eagleoflqj** [comment]
感谢！钦定了
自适应深浅我们会研究的
