### ISSUE TITLE
候选菜单面板无法显示 Lua 脚本 yield 出来的候选项

### ISSUE THREAD

**Issue by boomker** [fcitx-contrib/fcitx5-macos#145]
我有一个 Lua 脚本，用来在输入法候选菜单里显示一些 app 应用的名称，选中对应的 app 名称即可实现应用的启动和切换。
这个功能在鼠须管里是正常可用的， 但是用在小企鹅里，发现无法显示任何 app 应用名称。具体看下图：
鼠须管：
<img width="171" alt="image" src="https://github.com/fcitx-contrib/fcitx5-macos/assets/19751472/98f9c805-590f-48af-a640-64d547c1a6c8">

小企鹅：
<img width="158" alt="image" src="https://github.com/fcitx-contrib/fcitx5-macos/assets/19751472/7cfd2947-86d5-44dd-a38b-7454b15a7cac">

相同的代码和配置， 为何有不同的表现呢，希望大佬们帮忙看看问题出现在哪里呢？

涉及到 Lua 脚本和配置如下：
https://github.com/boomker/rime-fast-xhup/blob/ba415176fa887d060dfe213699f2429b58266de2/lua/launcher.lua
https://github.com/boomker/rime-fast-xhup/blob/ba415176fa887d060dfe213699f2429b58266de2/lua/launcher_config.lua

涉及到代码块：
https://github.com/boomker/rime-fast-xhup/blob/ba415176fa887d060dfe213699f2429b58266de2/lua/launcher.lua#L225-L260

**Comment by ksqsf** [comment]
这不是 f5m 的 bug。

问题出在 [`detect_os`](https://github.com/boomker/rime-fast-xhup/blob/ba415176fa887d060dfe213699f2429b58266de2/lua/launcher.lua#L35) 中只识别了 squirrel，所以在 f5m 上运行时（发行版名 `fcitx-rime`），系统没有被识别成 MacOS 而是 iOS，因此在 https://github.com/boomker/rime-fast-xhup/blob/ba415176fa887d060dfe213699f2429b58266de2/lua/launcher.lua#L255 中取到了[空的命令列表](https://github.com/boomker/rime-fast-xhup/blob/ba415176fa887d060dfe213699f2429b58266de2/lua/launcher_config.lua#L51)。

PS，还发现另外两个问题：
1. https://github.com/boomker/rime-fast-xhup/blob/ba415176fa887d060dfe213699f2429b58266de2/lua/pin_word.lua#L109：custom_phrase_tran:query 结果可能为 nil，需要防御。
2. https://github.com/boomker/rime-fast-xhup/blob/ba415176fa887d060dfe213699f2429b58266de2/lua/flypy_switcher.lua#L71：没有返回 kNoop。

由于 Lua 代码逻辑丰富多样，我们期望方案作者能首先自行调试（毕竟自己的自带肯定是自己最了解），然后给出比较具体的、与鼠须管的行为差异（比如某个具体的 API 接口返回值不同），这样可以节约很多时间，十分感谢理解与协助。

**Comment by boomker** [comment]
问题解决了，感谢大佬的指点，还贴心的帮我找出了其他存在的潜在🐛，万分感谢🙏。
在寻找 bug 的过程中，肯定让您费心了不少，浪费了一些时间，非常不好意思🙇‍♂️。
下次我多多测试验证后提 issue， 希望之后可以更好地向项目做出贡献。
