### ISSUE TITLE
“字母和数字后输入半角标点”功能和其他平台上的行为不一样

### ISSUE THREAD

**Issue by yintsyu** [fcitx-contrib/fcitx5-macos#161]
输入数字以后会出现半角标点，这个时候按退格，在其他平台上是在删除半角标点的同时上屏全角标点。而f5m上按退格只删除半角标点，要按下一个键才会把全角标点上屏，容易造成误判。
![QQ_f5mbug](https://github.com/fcitx-contrib/fcitx5-macos/assets/70472800/550951a1-416b-476c-b511-6e921a46a3bb)
小企鹅版本：495df97
系统版本：Sonoma 14.5

**Comment by eagleoflqj** [comment]
感谢汇报，已修复
