### ISSUE TITLE
scroll mode和普通模式的样式不一致

### ISSUE THREAD

**Issue by Seterplus** [fcitx-contrib/fcitx5-macos#205]
普通模式：
<img width="743" alt="image" src="https://github.com/user-attachments/assets/fbf916ba-b3d2-4fbb-bb9e-4e1f4686e57d">

scroll mode：
<img width="743" alt="image" src="https://github.com/user-attachments/assets/191edad4-4d4a-4291-bcea-4f7655e2d935">

序号一个有点一个没有点，导致打开scroll mode时第一行的词会有很大的抖动，不太美观 :)

**Comment by eagleoflqj** [comment]
Fixed at https://github.com/fcitx-contrib/fcitx5/commit/d2f26062734510586a70522acb1d02b4288c207b

**Comment by changzaicl** [comment]
scroll mode模式下，在预编辑区输入时，或有第一个字母向左移动的情况。
输入 “ce“，第一个字母”c“后，再输入”e“，字母”c“会向左移动一点点。

谢谢！

**Comment by eagleoflqj** [comment]
> scroll mode模式下，在预编辑区输入时，或有第一个字母向左移动的情况。 输入 “ce“，第一个字母”c“后，再输入”e“，字母”c“会向左移动一点点。

已修。这个 bug 和本 issue 无关，下次记得单开一条。
